version: "2.1"

networks:
  info:
    ipam:
      config:
        - subnet: 172.20.0.0/24
services:
  db:
    image: svcosti/infodb
    container_name: db
    volumes:
      - /opt/oracle/XE21CFULL/oradata:/oracle-volume
    environment:
      - ORACLE_PASSWORD=SysPassword1
      - ORACLE_USER='system'
    ports:
      - 1521:1521
    restart: unless-stopped
    networks:
      info:
        ipv4_address: 172.20.0.3

  web:
    image: web
    container_name: web
    environment: {}
    volumes: []
    ports:
      - 4443:4443
    restart: unless-stopped
    networks:
      info:
        ipv4_address: 172.20.0.2

